name: VelocityVanish
version: '${version}'
main: ir.syrent.velocityvanish.VelocityVanish
api-version: 1.13
authors: [ Syrent ]
description: Advanced vanish system
website: syrent.ir
softdepend: [PlaceholderAPI]