#
# Full wiki is available at https://github.com/Syrent/VelocityVanish/wiki
#
config_version: 4
default_language: en_US
show_dependency_suggestions: true
# NOT RECOMMENDED, Legacy code support is extremely discouraged. It affects performance, and it does not contain the new minecraft chat features.
support_legacy_color_codes: false
# If you are the first player to join the server, the Vanish data may not be synchronized correctly,
# and you will not be in vanish mode. This option allows you to enter vanish mode if you have operator privileges
# or the "velocityvanish.action.vanish.force" permission. If you were not previously in vanish mode,
# it will unvanish you after a few seconds.
force_vanish_if_first: true

bstats: true
# Leave sounds blank to disable them
# Example: command: ""
sounds:
    command: "ENTITY_EXPERIENCE_ORB_PICKUP"
    vanish: "ENTITY_EXPERIENCE_ORB_PICKUP"
    unvanish: "ENTITY_EXPERIENCE_ORB_PICKUP"
vanish:
    # Show players actionbar when they are vanished
    actionbar: true
    # Remember vanish data after switch servers?
    # Note: Need Velocity as proxy server and `velocity_support` enabled
    remember: true
    # Should we change player type to spectator in tablist for players who have permission to see vanished players?
    # Note: Requires ProtocolLib
    see_as_spectator: true
    # Should vanished players be protected from all damage sources?
    invincible: true
    # Prevent vanished players from pickup items
    prevent_pickup: true
    # Note: Not working when some ProCosmetics cosmetics are enabled!
    silent_open_container: true
    prevent:
        block_break: false
        block_place: false
        interact: false
