name: Bug Report
description: Unwanted behavior that does not match the configuration.
labels: ["Bug"]
body:
  - type: input
    attributes:
      label: Server backend version
      description: Version and type of used server software where VelocityVanish is installed.
      placeholder: Spigot 1.20.1
    validations:
      required: true
  - type: input
    attributes:
      label: Server backend Java version
      description: The version of Java that you use to run your backend server
      placeholder: Amazon Correto 17
    validations:
      required: true
      
  - type: input
    attributes:
      label: Server Velocity version
      description: Version and type of used server software where VelocityVanish is installed.
      placeholder: Velocity 3.1.1 build 98
    validations:
      required: true
      
  - type: input
    attributes:
      label: Server Velocity Java version
      description: The version of Java that you use to run your Velocity server
      placeholder: Amazon Correto 17
    validations:
      required: true

  - type: input
    attributes:
      label: VelocityVanish version
      description: Full version in numbers, "latest" is not a version.
      placeholder: 3.6.0
    validations:
      required: true

  - type: textarea
    attributes:
      label: Describe the bug
      description: How the plugin behaves
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected behavior
      description: How the plugin is supposed to behave instead of your configuration.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps to reproduce
      description: What to do in order to reproduce this issue
      placeholder: |
        Step 1: ..
        Step 2: ..
    validations:
      required: true

  - type: input
    attributes:
      label: LuckPerms webview link
      description: "I need it to check for any problem with your permissions (Leave it empty if you don't have LuckPerms)"
      placeholder: "https://luckperms.net/editor/y9hSFMj123"
    validations:
      required: false

  - type: textarea
    attributes:
      label: "VelocityVanish's configuration file"
      placeholder: |
        ```yml
        config_version: 6
        default_language: en_US
        show_dependency_suggestions: true
        
        support_legacy_color_codes: false
        
        force_vanish_if_first: true
        
        bstats: true
        
        sounds:
          command: ""
          vanish: ""
          unvanish: ""
        ```
    validations:
      required: true

  - type: textarea
    attributes:
      label: Plugins
      description: "List of the plugins on your backend server"
      placeholder: |
        EssentialsX, LuckPerms, Vault, VelocityVanish
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional info
      description: Any other info you want to provide, such as screenshots.
    validations:
      required: false
  - type: checkboxes
    attributes:
      label: Checklist
      description: Let's make sure this report is valid
      options:
        - label: I am running the latest version of the plugin on both Velocity and Spigot
          required: true
        - label: I have read the wiki to make sure it's not an issue with configuration
          required: true
        - label: I tried the plugin on a fresh server and it didn't work (Or it worked but I know exactly which plugin it's incompatible with)
          required: true
        - label: I ticked all of the boxes without actually reading them
          required: false
