name: Publish to Hangar
on:
  push:
    branches:
      - development
      - master

jobs:
  publish:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Change wrapper permissions
        run: chmod +x ./gradlew
      - name: Publish
        env:
          HANGAR_TOKEN: ${{ secrets.HANGAR_API_TOKEN }}
          HANGAR_BUILD_CHANNEL: Snapshot
        run: ./gradlew build publishPluginPublicationToHangar --stacktrace --debug --info --scan
